### PR TITLE
fix java IDE dependency

### LINKED ISSUE #10: Class not found exception running on WebStorm
Project import builder is most like available only on Java IDE, IntelliJ IDEA, and most likely not available on WebStorm, PhpStorm, PyCharm, CLion or RubyMine.

```
WebStorm 2018.1.4
Build #WS-181.5087.27, built on May 21, 2018
Licensed to Vladimir Schneider
Subscription is active until October 9, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

```
com/intellij/projectImport/ProjectImportBuilder
java.lang.NoClassDefFoundError: com/intellij/projectImport/ProjectImportBuilder
	at com.lid.intellij.translateme.configuration.ConfigurationComponent.createComponent(ConfigurationComponent.java:79)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:163)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.a(ConfigurableCardPanel.java:73)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.createConfigurableComponent(ConfigurableCardPanel.java:69)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:55)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:73)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:70)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:88)
	at com.intellij.ui.CardLayoutPanel.b(CardLayoutPanel.java:116)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.n(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:426)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1688)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1637)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:69)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:69)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:97)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:103)
	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.b(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.n(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### PR DESCRIPTION
**Pull request by vsch**
Great plugin.

I needed these changes ASAP. I have German Spec Docs in a WebStorm project, lots of German comments in the code and I don't speak German. 

The tooltip option shows translations in a tooltip to make translations not get in the way like the dialog does. You may want to add a timeout option in settings. I set to 60 seconds but moving caret or hitting escape will close it early.

This also fixes #10, I reported earlier.

* remove need for project from configuration state instance
* add show translations as tooltip
* fix NPE if auto detection fails and returns null
* add notification balloon group to allow user configuration

### CODE REVIEW

File: src/com/lid/intellij/translateme/actions/TranslateAction.java [hunk 1]
```diff
@@ -1,78 +1,125 @@
...
+        private void showErrorBalloon(Editor editor, String message) {
+            NOTIFICATION_GROUP.createNotification("TranslateMe Error", XmlStringUtil.wrapInHtml(message), NotificationType.ERROR, (notification, event) -> {
+            }).notify(null);
+        }
+
+        private void showTooltip(Editor editor, String message) {
+            //String text = "<table><tr><td>&nbsp;</td><td>$message</td><td>&nbsp;</td></tr></table>"
+            HintManagerImpl hintManager = (HintManagerImpl) HintManager.getInstance();
+            int flags = HintManager.HIDE_BY_CARET_MOVE | HintManager.UPDATE_BY_SCROLLING | HintManager.HIDE_BY_ESCAPE;
+            int timeout = 60000; // default 1min?
```
Comment (vvsevolodovich) [inline src/com/lid/intellij/translateme/actions/TranslateAction.java:92]: Configuration parameter? Or a constant at least

File: src/com/lid/intellij/translateme/actions/TranslateAction.java [hunk 2]
```diff
@@ -1,78 +1,125 @@
...
+            String html = HintUtil.prepareHintText(message, HintUtil.getInformationHint());
+
+            JComponent label = HintUtil.createInformationLabel(html, e -> {
```
Comment (vvsevolodovich) [inline src/com/lid/intellij/translateme/actions/TranslateAction.java:95]: This method should be moved to a separate class.

File: src/com/lid/intellij/translateme/configuration/ConfigurationComponent.java [hunk 3]
```diff
@@ -3,23 +3,23 @@
...
 import javax.swing.*;
 
-public final class ConfigurationComponent implements ProjectComponent, Configurable {
+public final class ConfigurationComponent implements Configurable {
 	public static final String COMPONENT_NAME = "Translate.ConfigurationComponent";
 //  private final ImageIcon CONFIG_ICON =
 //          helper.getIcon("resources/icon.png", getClass());
 
-	public static final String CONFIGURATION_LOCATION;
+	//public static final String CONFIGURATION_LOCATION;
```
Comment (vvsevolodovich) [inline src/com/lid/intellij/translateme/configuration/ConfigurationComponent.java:16]: Let's get rid of the commented code

**Review by vvsevolodovich — APPROVED** [review]
There are some improvements required, I will create the issues for them

**Comment by vsch** [comment]
@vlivanov, I added to my fork options to disable splitting on CamelCase and one to disable splitting on underscores. Not splitting on underscores prevents identifiers in the text from having their _ changed to spaces. 

I also improved the placement of the tooltip to limit max column to visible editor area. Otherwise long lines would mess up the placement.

I did not PR it because these are specific to my use but feel free to add the code to the plugin.

**Comment by vsch** [comment]
@vlivanov, forgot to mention that you should probably have an option for setting a personal Yandex key and limit use of your key to short texts. If your plugin gets popular it might hit the Yandex free monthly translation limit and then it will stop working for all users.

**Comment by vvsevolodovich** [comment]
@vsch Your PR on CamelCase would be more than welcome. 
Regarding the API key, yep, you're 100% right, I will implement it in the near future.

**Comment by vvsevolodovich** [comment]
@vsch Thanks for your current PR, I checked and it works great. I submitted a new version for the review, expect the plugin update in 1-2 days.
